FROM	node:lts-alpine AS vue

RUN		mkdir -p /app/frontend
WORKDIR	/app/frontend
COPY	./package*.json .
RUN		npm install
COPY	. .
RUN		npm run build
RUN		mkdir -p /var/www/
RUN		mv /app/frontend/dist /var/www/transcendance
