services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/app/
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - database
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app/frontend/
      - /app/frontend/node_modules/
    ports:
      - 5173:5173
    env_file:
      - ./.env.dev
    depends_on:
      - backend

  database:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.db.env.dev

volumes:
  postgres_data:
